org: kiranbusari
app: node-http-apis
service: node-http-apis
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: index.handler
    events:
      - httpApi:
          path: /hello
          method: get

  bye:
    handler: bye.handler
    events:
      - httpApi:
          path: /bye
          method: get
